version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: expense-tracker-app
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_DATABASE=expense_tracker
      - DB_USERNAME=expense_user
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    volumes:
      - storage_data:/var/www/html/backend/storage
      - cache_data:/var/www/html/backend/bootstrap/cache
    depends_on:
      - db
      - redis
    networks:
      - expense-tracker-network

  db:
    image: mysql:8.0
    container_name: expense-tracker-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=expense_tracker
      - MYSQL_USER=expense_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
    networks:
      - expense-tracker-network

  redis:
    image: redis:7-alpine
    container_name: expense-tracker-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - expense-tracker-network

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: expense-tracker-proxy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - DEFAULT_HOST=expense-tracker.local
    depends_on:
      - app
    networks:
      - expense-tracker-network

  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: expense-tracker-letsencrypt
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - nginx-proxy
    networks:
      - expense-tracker-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  storage_data:
    driver: local
  cache_data:
    driver: local
  certs:
    driver: local
  vhost:
    driver: local
  html:
    driver: local
  acme:
    driver: local

networks:
  expense-tracker-network:
    driver: bridge